module.exports = {
    run: [
      {
        method: "notify",
        params: {
          html: "This install script is generated by Gepeto. Please edit this file to customize the install process."
        }
      }
    ]
  }
