module.exports = {
  version: "2.0",
  title: "Gepeto Generated App",
  description: "This app was generated by Gepeto.",
  icon: "icon.png",
  menu: [{
    text: "Start",
    href: "start.js"
  }]
}
